<?php

declare(strict_types=1);

/**
 * Żargon SIWZ → frazy katalogu, per kategoria (pianki/szelki/ESD nie mieszają rodzin).
 * Trafienie w żargon zawsze dokłada frazy z cennika do wyszukiwania i do modelu.
 *
 * @return list<array{category: string, terms: list<string>, phrases: list<string>, note: string, jargon: bool}>
 */
$e = static function (
    string $category,
    array $terms,
    array $phrases,
    string $note = '',
    bool $jargon = false,
    array $keywords = [],
): array {
    return [
        'category' => $category,
        'terms' => $terms,
        'phrases' => $phrases,
        'note' => $note,
        'jargon' => $jargon,
        'keywords' => $keywords,
    ];
};

return [
    $e('rece', ['wampirki', 'wampiry'], ['rękawice dzianinowe powlekane', 'rękawice powlekane dłoń'], 'Proste dzianinowe, dłoń powlekana, ochrona przed cieczą.', true),
    $e('rece', ['gumówki', 'gumowane'], ['rękawice gumowe', 'rękawice powlekane gumą'], '', true),
    $e('rece', ['pianki'], ['rękawice powlekane pianką', 'rękawice nitryl pianka'], 'Powleczenie pianką, np. nitrylową.', true),
    $e('rece', ['nitryle', 'nitrylki', 'nitrylowe', 'nitryle robocze'], ['rękawice nitrylowe'], '', true),
    $e('rece', ['lateksy', 'lateksowe'], ['rękawice lateksowe'], '', true),
    $e('rece', ['winyle', 'winylówki', 'winylowe'], ['rękawice winylowe'], '', true),
    $e('rece', ['foliowe', 'foliówki'], ['rękawice foliowe', 'rękawice foliowe jednorazowe'], '', true),
    $e('rece', ['jednorazówki', 'jednorazowe'], ['rękawice jednorazowe'], '', true),
    $e('rece', ['kropki', 'nakrapiane'], ['rękawice nakrapiane PVC', 'rękawice z nakropieniem PVC'], '', true),
    $e('rece', ['PCV', 'PVC'], ['rękawice PVC', 'rękawice PCV'], '', true),
    $e('rece', ['olejówki'], ['rękawice olejoodporne', 'rękawice do oleju'], '', true),
    $e('rece', ['chemiczne'], ['rękawice chemiczne', 'rękawice EN 374'], ''),
    $e('rece', ['kwasówki', 'kwasoodporne'], ['rękawice kwasoodporne', 'rękawice chemiczne'], '', true),
    $e('rece', ['antyprzecięciowe', 'antycut', 'cuty'], ['rękawice antyprzecięciowe'], '', true),
    $e('rece', ['kevlarówki', 'kevlarowe'], ['rękawice kevlar', 'rękawice aramidowe'], '', true),
    $e('rece', ['metalówki'], ['rękawice antyprzecięciowe', 'rękawice z włóknem metalowym'], '', true),
    $e('rece', ['spawalnicze', 'spawalnicówki'], ['rękawice spawalnicze'], '', true),
    $e('rece', ['skórzane'], ['rękawice skórzane'], ''),
    $e('rece', ['dwoiny', 'dwoinowe'], ['rękawice dwoina', 'rękawice ze skóry dwoinowej'], '', true),
    $e('rece', ['licówki', 'licowe'], ['rękawice licowe', 'rękawice ze skóry licowej'], '', true),
    $e('rece', ['ocieplane', 'zimówki', 'zimowe robocze'], ['rękawice ocieplane', 'rękawice zimowe'], '', true),
    $e('rece', ['dzianiny', 'dziane'], ['rękawice dzianinowe'], '', true),
    $e('rece', ['montażówki', 'montażowe'], ['rękawice montażowe'], '', true),
    $e('rece', ['magazynówki'], ['rękawice magazynowe', 'rękawice montażowe'], '', true),
    $e('rece', ['budowlanki'], ['rękawice budowlane', 'rękawice robocze'], '', true),
    $e('rece', ['ogrodniczki'], ['rękawice ogrodnicze'], 'W odzieży ogrodniczki = spodnie.', true),
    $e('rece', ['chwytne'], ['rękawice z przyczepnością', 'rękawice montażowe'], '', true),
    $e('rece', ['antywibracyjne', 'wibracyjne'], ['rękawice antywibracyjne'], ''),
    $e('rece', ['ESD', 'antystatyki', 'rękawice antyelektrostatyczne'], ['rękawice antystatyczne', 'rękawice ESD'], ''),
    $e('rece', ['rękawice elektryczne', 'dielektryczne', 'elektroizolacyjne'], ['rękawice elektroizolacyjne'], ''),
    $e('rece', ['rękawice do metalu', 'rękawice do blachy', 'rękawice do szkła'], ['rękawice antyprzecięciowe'], ''),
    $e('rece', ['rękawice do chłodni', 'rękawice do mroźni'], ['rękawice zimowe', 'rękawice termiczne'], ''),
    $e('rece', ['rękawice do pieca', 'żaroodporne', 'termiczne', 'rękawice do pieczenia'], ['rękawice termiczne', 'rękawice żaroodporne'], ''),
    $e('rece', ['rękawice rzeźnicze', 'rękawice masarskie'], ['rękawice antyprzecięciowe spożywcze'], ''),
    $e('rece', ['rękawice siatkowe', 'rękawice łańcuchowe'], ['rękawice metalowe siatkowe', 'rękawice łańcuchowe'], ''),
    $e('rece', ['rękawice do piaskowania'], ['rękawice do piaskowania'], ''),
    $e('rece', ['rękawice długie', 'mankietówki'], ['rękawice z długim mankietem'], '', true),
    $e('rece', ['narękawniki', 'rękawy'], ['narękawniki', 'rękawy ochronne'], '', true),
    $e('rece', ['antyigłowe', 'antykolcowe'], ['rękawice odporne na przekłucie'], ''),
    $e('rece', ['pazurki'], ['rękawice ogrodnicze z pazurkami'], '', true),
    $e('rece', ['rękawice do lasu', 'rękawice dla pilarza', 'rękawice pilarza'], ['rękawice dla pilarza'], ''),
    $e('rece', ['rękawice do kosy'], ['rękawice do kosy'], ''),
    $e('rece', ['rękawice kierowcy', 'samochodówki'], ['rękawice dla kierowcy', 'rękawice warsztatowe'], '', true),
    $e('rece', ['mechaniki', 'mechaniczne', 'warsztatówki'], ['rękawice mechanika', 'rękawice warsztatowe'], '', true),
    $e('rece', ['taktyczne'], ['rękawice taktyczne'], '', true),

    $e('glowa', ['kask', 'hełm', 'kask budowlany'], ['hełm ochronny'], '', true),
    $e('glowa', ['budowlany', 'budowlanka'], ['hełm budowlany'], '', true),
    $e('glowa', ['kask z daszkiem'], ['hełm ochronny z daszkiem'], ''),
    $e('glowa', ['skorupa'], ['skorupa hełmu'], '', true),
    $e('glowa', ['kask leśnika', 'kask pilarza'], ['hełm dla pilarza', 'hełm leśny'], ''),
    $e('glowa', ['kask z nausznikami'], ['hełm z nausznikami'], ''),
    $e('glowa', ['kask z przyłbicą', 'kask z wizjerem'], ['hełm z osłoną twarzy'], ''),
    $e('glowa', ['kask elektryka'], ['hełm elektroizolacyjny'], ''),
    $e('glowa', ['kask bez daszka', 'kask wspinaczkowy', 'hełm wysokościowy'], ['hełm do pracy na wysokości'], ''),
    $e('glowa', ['baseballówka', 'bejsbolówka', 'bump cap', 'bump', 'czapka z wkładką'], ['czapka ochronna', 'czapka przeciwuderzeniowa', 'lekki hełm przemysłowy'], '', true, ['czapka', 'bejsbolówka', 'hełm']),
    $e('glowa', ['siatka'], ['siatka do włosów'], '', true),
    $e('glowa', ['czepek'], ['czepek ochronny'], ''),
    $e('glowa', ['kominiarka', 'kominiarka robocza'], ['kominiarka ochronna'], ''),
    $e('glowa', ['kaptur', 'kaptur spawalniczy'], ['kaptur ochronny'], ''),

    $e('oczy', ['bezpieczniki', 'bhp-ki', 'bryle'], ['okulary ochronne'], '', true, ['okulary', 'bryle']),
    $e('oczy', ['gogle', 'gogale', 'gogielki'], ['gogle ochronne'], '', true),
    $e('oczy', ['przeciwodpryskowe'], ['okulary przeciwodpryskowe', 'gogle przeciwodpryskowe'], ''),
    $e('oczy', ['przeciwpyłowe'], ['gogle przeciwpyłowe'], ''),
    $e('oczy', ['chemiczne', 'szczelne'], ['gogle chemiczne'], ''),
    $e('oczy', ['przyciemniane', 'przeciwsłoneczne'], ['okulary ochronne przeciwsłoneczne'], ''),
    $e('oczy', ['okulary spawalnicze', 'spawalnicze'], ['okulary spawalnicze', 'przyłbica spawalnicza'], ''),
    $e('oczy', ['laserówki', 'okulary do lasera'], ['okulary laserowe'], '', true),
    $e('oczy', ['okulary korekcyjne BHP', 'nakładki', 'OTG'], ['okulary ochronne nakładane', 'okulary OTG'], '', true),
    $e('oczy', ['gogle narciarskie'], ['gogle ochronne'], '', true),

    $e('twarz', ['przyłbica', 'wizjer', 'osłona twarzy'], ['osłona twarzy', 'przyłbica ochronna'], '', true),
    $e('twarz', ['szybka', 'plexi', 'przyłbica uchylna'], ['przyłbica ochronna', 'osłona twarzy'], '', true),

    $e('spawanie', ['przyłbica spawalnicza', 'maska spawalnicza', 'spawalnicza'], ['przyłbica spawalnicza'], '', true),
    $e('spawanie', ['automat', 'automat spawalniczy', 'samościemniająca', 'samościemniacz'], ['przyłbica samościemniająca'], '', true),
    $e('spawanie', ['kaptur spawalniczy'], ['kaptur spawalniczy'], ''),
    $e('spawanie', ['filtry spawalnicze', 'szybki spawalnicze'], ['filtry do przyłbicy spawalniczej'], ''),
    $e('spawanie', ['skóra spawalnicza', 'fartuch spawalniczy'], ['odzież spawalnicza', 'fartuch spawalniczy'], ''),
    $e('spawanie', ['narękawniki spawalnicze'], ['narękawniki spawalnicze'], ''),
    $e('spawanie', ['rękawice spawalnicze'], ['rękawice spawalnicze'], ''),

    $e('sluch', ['słuchawki', 'nauszniki', 'nauszniki BHP', 'przeciwhałasowe'], ['nauszniki przeciwhałasowe', 'ochronniki słuchu'], '', true),
    $e('sluch', ['stopery', 'zatyczki', 'korki', 'stoperki'], ['wkładki przeciwhałasowe'], '', true),
    $e('sluch', ['pianki', 'piankowe'], ['wkładki piankowe przeciwhałasowe'], '', true),
    $e('sluch', ['sznurki', 'sznurkowe'], ['wkładki przeciwhałasowe ze sznurkiem'], '', true),
    $e('sluch', ['pałąkowe', 'pałąk'], ['ochronniki słuchu na pałąku'], '', true),
    $e('sluch', ['kaskowe'], ['nauszniki do hełmu'], '', true),
    $e('sluch', ['aktywne', 'elektroniczne', 'komunikacyjne', 'radiowe'], ['aktywne ochronniki słuchu'], ''),

    $e('oddech', ['maska', 'maseczka'], ['półmaska', 'maska filtrująca'], '', true),
    $e('oddech', ['pyłówka', 'przeciwpyłówka', 'przeciwpyłowa'], ['półmaska przeciwpyłowa', 'maska przeciwpyłowa'], '', true),
    $e('oddech', ['FFP', 'FFP1', 'FFP2', 'FFP3', 'maseczka FFP2', 'maseczka FFP3'], ['półmaska filtrująca FFP'], ''),
    $e('oddech', ['z zaworkiem'], ['półmaska z zaworem'], ''),
    $e('oddech', ['bez zaworka'], ['półmaska bez zaworu'], ''),
    $e('oddech', ['półmaska'], ['półmaska wielorazowa'], ''),
    $e('oddech', ['pełnotwarzówka', 'pełna maska', 'maska gazowa'], ['maska pełnotwarzowa'], '', true),
    $e('oddech', ['pochłaniacz'], ['pochłaniacz do maski'], ''),
    $e('oddech', ['filtr', 'filtry', 'filtry gazowe', 'filtry pyłowe'], ['filtr do półmaski'], ''),
    $e('oddech', ['wąsy'], ['filtry do półmaski'], 'Żargon na elementy filtracyjne.', true),
    $e('oddech', ['maska malarska', 'maska lakiernicza'], ['półmaska malarska'], '', true),
    $e('oddech', ['maska chemiczna'], ['półmaska chemiczna', 'maska chemiczna'], ''),
    $e('oddech', ['maska do oprysków'], ['półmaska do oprysków'], ''),

    $e('chemia', ['kombinezon chemiczny', 'chemiczny', 'chemik'], ['kombinezon chemiczny'], ''),
    $e('chemia', ['kwasoodporny', 'kwasówka'], ['odzież kwasoodporna', 'kombinezon chemiczny'], '', true),
    $e('chemia', ['fartuch chemiczny', 'fartuch kwasoodporny', 'gumowy fartuch'], ['fartuch chemiczny'], ''),
    $e('chemia', ['PCV', 'PVC', 'gumowy'], ['odzież ochronna PVC'], ''),
    $e('chemia', ['Tyvek', 'tyvek'], ['kombinezon Tyvek'], '', true),
    $e('chemia', ['gazoszczelny', 'kwasoodporny kombinezon'], ['kombinezon gazoszczelny', 'kombinezon chemiczny'], ''),
    $e('chemia', ['pyłochronny'], ['kombinezon pyłochronny'], ''),
    $e('chemia', ['sorbent', 'mata sorpcyjna', 'rękaw sorpcyjny', 'poduszka sorpcyjna', 'granulat'], ['sorbent', 'mata sorpcyjna'], ''),
    $e('chemia', ['neutralizator'], ['neutralizator substancji chemicznych'], ''),

    $e('odziez', ['deszczówka', 'przeciwdeszczówka', 'sztormiak', 'gumówka', 'gumowiec', 'peleryna'], ['odzież przeciwdeszczowa', 'kurtka przeciwdeszczowa'], '', true),
    $e('odziez', ['płaszcz'], ['płaszcz przeciwdeszczowy'], '', true),
    $e('odziez', ['fluo', 'fluorescencyjne', 'odblaski', 'odblaskowe', 'żółtki', 'pomarańczowe'], ['odzież ostrzegawcza', 'kamizelka ostrzegawcza'], '', true),
    $e('odziez', ['kamizelka', 'odblaskowa kamizelka'], ['kamizelka ostrzegawcza'], '', true),
    $e('odziez', ['drelich', 'drelichy'], ['odzież drelichowa', 'ubranie robocze'], 'Tkanina, nie osobny asortyment.', true),
    $e('odziez', ['szelki', 'ogrodniczki'], ['spodnie ogrodniczki', 'spodnie robocze na szelkach'], 'Na wysokości szelki = asekuracja.', true, ['ogrodniczki', 'spodnie']),
    $e('odziez', ['spodnie do pasa', 'spodnie robocze'], ['spodnie robocze'], '', true, ['spodnie']),
    $e('odziez', ['bluza', 'robocza bluza'], ['bluza robocza'], '', true, ['bluza']),
    $e('odziez', ['bojówki', 'cargo', 'portki'], ['spodnie robocze cargo'], '', true),
    $e('odziez', ['polar', 'polarek', 'polar roboczy'], ['bluza polarowa'], '', true),
    $e('odziez', ['softshell'], ['kurtka softshell'], ''),
    $e('odziez', ['wiatrówka'], ['kurtka przeciwwiatrowa'], '', true),
    $e('odziez', ['ocieplana', 'zimówka'], ['kurtka ocieplana', 'kurtka zimowa'], '', true),
    $e('odziez', ['bezrękawnik', 'kamizelka ocieplana'], ['kamizelka ocieplana'], '', true),
    $e('odziez', ['termo', 'termoaktywne', 'kalesony'], ['bielizna termiczna', 'odzież termoaktywna'], '', true),
    $e('odziez', ['pajac', 'jednoczęściówka'], ['kombinezon roboczy'], '', true),
    $e('odziez', ['dwuczęściówka'], ['komplet kurtka spodnie'], '', true),
    $e('odziez', ['kwasówka'], ['odzież kwasoodporna'], '', true),
    $e('odziez', ['trudnopalne', 'ognioodporne'], ['odzież trudnopalna'], ''),
    $e('odziez', ['antystatyczne', 'ESD'], ['odzież antystatyczna'], ''),
    $e('odziez', ['spawalnicze', 'skórzane'], ['odzież spawalnicza'], ''),
    $e('odziez', ['spodnie pilarza', 'pilarzówki', 'leśne', 'antyprzecięciowe'], ['odzież dla pilarza', 'spodnie antyprzecięciowe'], '', true),
    $e('odziez', ['zapaska'], ['fartuch gastronomiczny'], '', true),

    $e('ratownictwo', ['kamizelka asekuracyjna', 'kapok'], ['kamizelka ratunkowa', 'kamizelka asekuracyjna'], '', true),

    $e('wysokosc', ['szelki', 'uprząż', 'pełna uprząż', 'szelki pilarza'], ['szelki bezpieczeństwa', 'uprząż bezpieczeństwa'], '', true),
    $e('wysokosc', ['pas', 'biodrówka'], ['pas bezpieczeństwa', 'pas podtrzymujący'], '', true),
    $e('wysokosc', ['linka', 'lonża', 'lina'], ['linka bezpieczeństwa'], '', true),
    $e('wysokosc', ['amortyzator', 'absorber'], ['amortyzator upadku'], ''),
    $e('wysokosc', ['przyrząd samozaciskowy', 'bloczek'], ['urządzenie samozaciskowe'], ''),
    $e('wysokosc', ['zatrzaśnik', 'karabinek'], ['zatrzaśnik', 'karabinek bezpieczeństwa'], ''),
    $e('wysokosc', ['kotwa', 'punkt kotwiczący'], ['punkt kotwiczenia'], ''),
    $e('wysokosc', ['asekuracja', 'antyupadkowe', 'wysokościówka'], ['sprzęt chroniący przed upadkiem'], '', true),

    $e('stopy', ['trzewiki', 'glany', 'glany robocze'], ['trzewiki', 'buty robocze za kostkę'], '', true),
    $e('stopy', ['półbuty'], ['półbuty robocze'], ''),
    $e('stopy', ['sandały'], ['sandały robocze'], ''),
    $e('stopy', ['bezpieczniki', 'blachy', 'stalówki', 'stalowe noski', 'podnoski'], ['buty z podnoskiem', 'obuwie z podnoskiem'], '', true),
    $e('stopy', ['kompozyty', 'kompozytowe'], ['buty z podnoskiem kompozytowym'], '', true),
    $e('stopy', ['S1', 'S1P', 'S2', 'S3', 'S4', 'S5'], ['obuwie ochronne'], ''),
    $e('stopy', ['gumowce', 'kalosze', 'kaloszki'], ['kalosze', 'buty gumowe'], '', true),
    $e('stopy', ['gumofilce', 'gumofilce zimowe'], ['gumofilce', 'kalosze ocieplane'], '', true),
    $e('stopy', ['wodery'], ['wodery'], '', true),
    $e('stopy', ['pianki', 'neopreny'], ['obuwie neoprenowe'], '', true),
    $e('stopy', ['zimówki', 'ocieplane'], ['obuwie zimowe', 'obuwie ocieplane'], '', true),
    $e('stopy', ['antypoślizgowe'], ['obuwie antypoślizgowe'], ''),
    $e('stopy', ['olejoodporne'], ['obuwie olejoodporne'], ''),
    $e('stopy', ['chemiczne', 'kwasoodporne'], ['obuwie chemoodporne'], ''),
    $e('stopy', ['elektroizolacyjne', 'dielektryczne', 'buty dla elektryka'], ['obuwie elektroizolacyjne'], ''),
    $e('stopy', ['ESD', 'antystatyki'], ['obuwie ESD', 'obuwie antystatyczne'], ''),
    $e('stopy', ['wkładki', 'ortopedyczne', 'żelówki', 'ocieplacze'], ['wkładki do obuwia'], '', true),
    $e('stopy', ['gumowe ochraniacze', 'ochraniacze na buty'], ['ochraniacze na obuwie'], ''),
    $e('stopy', ['buty pilarza', 'pilarzówki'], ['buty dla pilarza'], '', true),
    $e('stopy', ['buty spawalnicze'], ['buty spawalnicze'], ''),
    $e('stopy', ['buty do chłodni', 'buty do mroźni'], ['buty do chłodni'], ''),

    $e('cialo', ['nakolanniki', 'kolanówki', 'kolana'], ['nakolanniki'], '', true),
    $e('cialo', ['nałokietniki', 'naramienniki', 'nagolenniki', 'ochraniacze goleni'], ['ochraniacze'], '', true),
    $e('cialo', ['pas lędźwiowy', 'pas kręgosłupa', 'pas biodrowy'], ['pas lędźwiowy'], ''),
    $e('cialo', ['pas monterski', 'uprząż monterska'], ['pas monterski'], '', true),
    $e('cialo', ['fartuch rzeźniczy', 'fartuch masarski', 'fartuch PCV', 'fartuch gumowy'], ['fartuch ochronny'], ''),
    $e('cialo', ['rękaw', 'narękawnik'], ['narękawnik', 'rękaw ochronny'], '', true),
    $e('cialo', ['osłona karku', 'osłona szyi', 'napierśnik'], ['osłona karku'], ''),
    $e('cialo', ['kamizelka ochronna', 'kamizelka kuloodporna', 'kamizelka taktyczna', 'kamizelka antyprzebiciowa'], ['kamizelka ochronna'], ''),
    $e('cialo', ['kevlar', 'aramid', 'kuloodporna', 'balistyka'], ['ochrona aramidowa', 'ochrona balistyczna'], ''),

    $e('promieniowanie', ['fartuch ołowiany', 'ołów', 'kołnierz ołowiany', 'rękawice ołowiane', 'okulary ołowiane'], ['fartuch ołowiany', 'ochrona radiologiczna'], ''),
    $e('promieniowanie', ['detektor', 'dozymetr'], ['dozymetr'], ''),

    $e('higiena', ['czepek', 'siatka na włosy'], ['czepek jednorazowy', 'siatka na włosy'], ''),
    $e('higiena', ['ochraniacze na buty', 'nakładki'], ['ochraniacze na obuwie jednorazowe'], '', true),
    $e('higiena', ['zarzutki', 'jednorazówka', 'kombinezon jednorazowy', 'biały kombinezon'], ['kombinezon jednorazowy'], '', true),
    $e('higiena', ['foliowy', 'włóknina', 'SMS'], ['odzież jednorazowa włóknina'], '', true),
    $e('higiena', ['czyściwo'], ['czyściwo przemysłowe'], ''),
    $e('higiena', ['fartuch laboratoryjny', 'fartuch lab'], ['fartuch laboratoryjny'], ''),

    $e('esd', ['antyelektrostatyczny', 'ESD'], ['odzież ESD', 'antystatyczne'], ''),
    $e('esd', ['opaska', 'opaska na rękę'], ['opaska ESD'], '', true),
    $e('esd', ['uziemienie', 'mata ESD'], ['mata ESD', 'uziemienie ESD'], ''),
    $e('esd', ['buty ESD'], ['obuwie ESD'], ''),
    $e('esd', ['fartuch ESD'], ['fartuch ESD'], ''),
    $e('esd', ['rękawiczki ESD'], ['rękawice ESD'], ''),

    $e('pierwsza_pomoc', ['apteczka', 'apteczka BHP', 'apteczka zakładowa', 'R1'], ['apteczka pierwszej pomocy'], '', true),
    $e('pierwsza_pomoc', ['AED', 'defibrylator'], ['defibrylator AED'], ''),
    $e('pierwsza_pomoc', ['plaster', 'opatrunek', 'bandaż', 'kompres'], ['opatrunek'], ''),
    $e('pierwsza_pomoc', ['folia NRC', 'termiczna', 'koc ratunkowy'], ['folia NRC', 'koc termiczny'], '', true),
    $e('pierwsza_pomoc', ['ustnik', 'maseczka do RKO', 'resuscytacyjna'], ['maska do RKO'], '', true),
    $e('pierwsza_pomoc', ['płukanka', 'eyewash', 'oczomyjka', 'myjka do oczu'], ['płyn do płukania oczu', 'oczomyjka'], '', true),
    $e('pierwsza_pomoc', ['prysznic bezpieczeństwa'], ['prysznic bezpieczeństwa'], ''),
];
