<?php

declare(strict_types=1);

return [
    /*
    | Oficjalne domeny producentów — certyfikaty / deklaracje / datasheet PDF.
    | Klucz = znormalizowana nazwa marki (małe litery, myślniki).
    */
    'manufacturer_domains' => [
        'demar' => ['demar.com.pl', 'www.demar.com.pl'],
        'atg' => [
            'atggloves.com',
            'www.atggloves.com',
            'atg-glovesolutions.com',
            'www.atg-glovesolutions.com',
        ],
        // aliasy marek ATG w cennikach / nazwach
        'maxiflex' => [
            'atggloves.com',
            'www.atggloves.com',
            'atg-glovesolutions.com',
            'www.atg-glovesolutions.com',
        ],
        'maxicut' => [
            'atggloves.com',
            'www.atggloves.com',
            'atg-glovesolutions.com',
            'www.atg-glovesolutions.com',
        ],
        'maxidry' => [
            'atggloves.com',
            'www.atggloves.com',
            'atg-glovesolutions.com',
            'www.atg-glovesolutions.com',
        ],
        'ansell' => ['ansell.com', 'www.ansell.com'],
        'delta-plus' => ['delta-plus.com', 'www.delta-plus.com', 'deltaplus.eu', 'www.deltaplus.eu'],
        'delta' => ['delta-plus.com', 'www.delta-plus.com', 'deltaplus.eu', 'www.deltaplus.eu'],
        'uvex' => [
            'uvex-safety.com',
            'www.uvex-safety.com',
            'uvex.com',
            'www.uvex.com',
            'uvex-safety.de',
            'www.uvex-safety.de',
            'uvex.de',
            // CDN zostaje — PDF/zdjęcia Uvex; indeks i lista admina je pomijają
            'd3nan4w00fsv2d.cloudfront.net',
            'd3rbxgeqn1ye9j.cloudfront.net',
        ],
        '3m' => ['3m.com', 'www.3m.com'],
        'honeywell' => [
            'honeywell.com',
            'www.honeywell.com',
            'sps.honeywell.com',
            'automation.honeywell.com',
            'www.automation.honeywell.com',
        ],
        'msa' => [
            'pl.msasafety.com',
            'msasafety.com',
            'www.msasafety.com',
        ],
        'msa-safety' => [
            'pl.msasafety.com',
            'msasafety.com',
            'www.msasafety.com',
        ],
        'msa-auer' => [
            'pl.msasafety.com',
            'msasafety.com',
            'www.msasafety.com',
        ],
        'portwest' => ['portwest.com', 'www.portwest.com'],
        'coverguard' => ['coverguard.com', 'www.coverguard.com'],
        'singer' => ['singer.fr', 'www.singer.fr'],
        'pros' => ['pros.pl', 'www.pros.pl'],
        'aj-group' => ['pros.pl', 'www.pros.pl'],
        'ajgroup' => ['pros.pl', 'www.pros.pl'],
        'urgent' => [
            'urgent.com.pl',
            'www.urgent.com.pl',
            'urgent.pl',
            'www.urgent.pl',
        ],
        'pilne' => [
            'urgent.com.pl',
            'www.urgent.com.pl',
            'urgent.pl',
            'www.urgent.pl',
        ],
        'kcl' => ['kcl.de', 'www.kcl.de'],
        'rostaing' => ['rostaing.com', 'www.rostaing.com'],
        'gvs' => [
            'gvs-rpb.com',
            'www.gvs-rpb.com',
            'rpb.com',
            'www.rpb.com',
            'gvs.com',
            'www.gvs.com',
            'gvs-elipse.com',
            'www.gvs-elipse.com',
        ],
        'rpb' => [
            'rpb.com',
            'www.rpb.com',
            'gvs-rpb.com',
            'www.gvs-rpb.com',
        ],
        'sordin' => [
            'sordin.com',
            'www.sordin.com',
            'hellberg-safety.com',
            'www.hellberg-safety.com',
        ],
        'hellberg' => [
            'hellberg-safety.com',
            'www.hellberg-safety.com',
            'sordin.com',
            'www.sordin.com',
        ],
        'weldas' => ['weldaseurope.com', 'www.weldaseurope.com', 'weldas.com', 'www.weldas.com'],
        'mapa' => [
            'mapa-pro.pl',
            'www.mapa-pro.pl',
            'mapa-pro.com',
            'www.mapa-pro.com',
        ],
        'cxs' => ['cxs.net.pl', 'www.cxs.net.pl', 'cxs.cz', 'www.cxs.cz', 'canis.cz', 'www.canis.cz'],
        'canis' => ['cxs.net.pl', 'www.cxs.net.pl', 'cxs.cz', 'www.cxs.cz', 'canis.cz', 'www.canis.cz'],
        'medibut' => ['medibut.pl', 'www.medibut.pl'],
        'reis' => ['reis.pl', 'www.reis.pl', 'reis.eu', 'www.reis.eu'],
        'panther' => [
            'panther-safety.com',
            'www.panther-safety.com',
            'panther-bhp.pl',
            'www.panther-bhp.pl',
        ],
        'ejendals' => [
            'ejendals.com',
            'www.ejendals.com',
            'jalas.com',
            'www.jalas.com',
        ],
        'jalas' => [
            'jalas.com',
            'www.jalas.com',
            'ejendals.com',
            'www.ejendals.com',
        ],
        'ardon' => ['ardon.pl', 'www.ardon.pl', 'ardon.cz', 'www.ardon.cz'],
        'ardon-safety' => ['ardon.pl', 'www.ardon.pl', 'ardon.cz', 'www.ardon.cz'],
        'marel' => ['marelplus.pl', 'www.marelplus.pl'],
        'marel-plus' => ['marelplus.pl', 'www.marelplus.pl'],
        'worklink' => ['worklink.com.pl', 'www.worklink.com.pl'],
        'supertech' => ['worklink.com.pl', 'www.worklink.com.pl'],
        'showa' => ['showa-glove.com', 'www.showa-glove.com', 'showagroup.com', 'www.showagroup.com'],
        'lebon' => ['lebonprotection.com', 'www.lebonprotection.com'],
        'cederroth' => ['cederroth.com', 'www.cederroth.com'],
        'sir-safety' => ['sirsafety.com', 'www.sirsafety.com', 'sir-safety.com', 'www.sir-safety.com'],
        'sir' => ['sirsafety.com', 'www.sirsafety.com', 'sir-safety.com', 'www.sir-safety.com'],
        'safeline' => ['safeline.pl', 'www.safeline.pl', 'medicline.pl', 'www.medicline.pl'],
        'i-a-arbeitsschutz' => ['safeline.pl', 'www.safeline.pl', 'medicline.pl', 'www.medicline.pl'],
        'secubox' => ['secubox.eu', 'www.secubox.eu', 'secubox.pl', 'www.secubox.pl'],
        'planam' => ['planam.de', 'www.planam.de'],
        'ox-on' => ['ox-on.com', 'www.ox-on.com'],
        'elten' => ['elten.com', 'www.elten.com'],
        'jori' => ['elten.com', 'www.elten.com'],
        'ppo' => ['ppo.pl', 'www.ppo.pl'],
        'u-power' => ['u-power.ai', 'u-power.it', 'www.u-power.it'],
        'dupont' => ['dupont.com', 'www.dupont.com', 'safespec.dupont.com'],
        'dickies' => ['dickies.com', 'www.dickies.com'],
        'julex' => ['julex.pl', 'www.julex.pl'],
        'jagatex' => ['jagatex.pl', 'www.jagatex.pl'],
        'greno' => ['greno.pl', 'www.greno.pl'],
        'polstar' => ['polstar.com.pl', 'www.polstar.com.pl'],
        'polrok' => ['polrok.com', 'www.polrok.com', 'polrok.pl', 'www.polrok.pl'],
        'zwoltex' => ['zwoltex.pl', 'www.zwoltex.pl'],
        'galmag' => ['galmag.pl', 'www.galmag.pl'],
        'maskpol' => ['maskpol.com.pl', 'www.maskpol.com.pl'],
        'secura' => ['securabc.com', 'www.securabc.com', 'secura.com.pl', 'www.secura.com.pl'],
        'termoizol' => ['termoizol.pl', 'www.termoizol.pl'],
        'alwit' => ['alwit.pl', 'www.alwit.pl'],
        'js-gloves' => ['js-gloves.pl', 'www.js-gloves.pl'],
        'filter-service' => ['filter-service.eu', 'www.filter-service.eu'],
        'boxmet' => ['boxmetmedical.pl', 'www.boxmetmedical.pl', 'boxmet.com.pl', 'www.boxmet.com.pl'],
        'cofra' => ['cofra.it', 'www.cofra.it'],
        'pip' => ['protectiveindustrialproducts.com', 'www.protectiveindustrialproducts.com'],
        'york' => ['york.pl', 'www.york.pl'],
        'gloria' => ['gloria.de', 'www.gloria.de'],
        'plum' => ['plum.eu', 'www.plum.eu', 'plum.dk', 'www.plum.dk'],
        'stoko' => ['scjp.com', 'www.scjp.com'],
        'deb' => ['scjp.com', 'www.scjp.com', 'debgroup.com', 'www.debgroup.com'],
        'deb-stoko' => ['scjp.com', 'www.scjp.com', 'debgroup.com', 'www.debgroup.com'],
        'cerva' => ['cerva.cz', 'www.cerva.cz', 'cerva.com', 'www.cerva.com'],
        'coba' => ['coba.com', 'www.coba.com'],
        'coba-europe' => ['coba.com', 'www.coba.com'],
        'arelax' => ['artra.com', 'www.artra.com'],
        'artra' => ['artra.com', 'www.artra.com'],
        'lemaitre' => ['lemaitre-securite.com', 'www.lemaitre-securite.com'],
        'mercator' => ['emercator.com', 'www.emercator.com'],
        'ogniochron' => ['ogniochron.eu', 'www.ogniochron.eu'],
        'agnes' => ['pwagnes.pl', 'www.pwagnes.pl'],
        'mat' => ['mat.konin.pl', 'www.mat.konin.pl'],
        'kask' => ['kask-safety.com', 'www.kask-safety.com'],
        'rs-arbeitsschutz' => ['rs-schutz.com', 'www.rs-schutz.com'],
        'irudek' => ['irudek.com', 'www.irudek.com'],
        'infield' => ['infield-safety.com', 'www.infield-safety.com'],
        'eider' => ['cerva.com', 'www.cerva.com', 'cerva.cz', 'www.cerva.cz'],
        'resin' => ['kortechpolska.pl', 'www.kortechpolska.pl'],
        'faraone' => ['faraone.pl', 'www.faraone.pl'],
        'perfect-fit' => [
            'automation.honeywell.com',
            'www.automation.honeywell.com',
        ],
    ],

    /*
    | Hosty do zapytań site: (katalog + sklepy, które ten asortyment indeksują).
    | Gdy brak wpisu, bierzemy manufacturer_domains.
    */
    'catalog_search_hosts' => [
        '3m' => [
            '3m.com',
        ],
        'ardon' => [
            'ardon.pl',
            'behapownia.pl',
            'specto.com.pl',
            'kams.com.pl',
            'aitbhp.pl',
            'optimumbhp.pl',
            'ardon.cz',
        ],
        'panther' => [
            'panther-bhp.pl',
            'panther-safety.com',
        ],
        'safeline' => [
            'safeline.pl',
            'medicline.pl',
        ],
        'i-a-arbeitsschutz' => [
            'safeline.pl',
            'medicline.pl',
        ],
        'mat' => [
            'mat.konin.pl',
        ],
        'honeywell' => [
            'automation.honeywell.com',
            'honeywell.com',
            'sps.honeywell.com',
        ],
        'delta-plus' => [
            'deltaplus.eu',
            'delta-plus.com',
        ],
        'delta' => [
            'deltaplus.eu',
            'delta-plus.com',
        ],
        'mapa' => [
            'mapa-pro.pl',
            'icd.pl',
        ],
        'marel' => [
            'marelplus.pl',
        ],
        'gvs' => [
            'idsblast.com',
            'blastone.com',
            'novarlo.com',
            'icd.pl',
            'gvs-rpb.com',
            'rpb.com',
        ],
        'rpb' => [
            'idsblast.com',
            'blastone.com',
            'novarlo.com',
            'rpb.com',
            'gvs-rpb.com',
        ],
        'atlas' => [
            'antar.pl',
            'promocjabhp.pl',
            'roboczystyl.pl',
            'optimumbhp.pl',
            'bpbhp.pl',
            'paktbhp.pl',
            'jaskon.pl',
            'regera.pl',
            'sklep.renex.pl',
            'behapownia.pl',
        ],
        'sordin' => [
            'customguns.pl',
            'hellberg-safety.com',
        ],
        'hellberg' => [
            'customguns.pl',
            'hellberg-safety.com',
        ],
        'cabinaid' => [
            'gvarant.pl',
            'optimumbhp.pl',
            'bpbhp.pl',
            'behapownia.pl',
        ],
    ],

    /*
    | Sklepy / dystrybutorzy — dobre źródła opisów (nie certyfikatów).
    */
    'retailer_domains' => [
        'idsblast.com',
        'blastone.com',
        'novarlo.com',
        'icd.pl',
        'supon.rzeszow.pl',
        'sprzetbhp.pl',
        'gvarant.pl',
        'bhponline-24.pl',
        'fasterbhp.pl',
        'bhp-sklep.com.pl',
        'bogarobhp.pl',
        'demar24.pl',
        'roboczystyl.pl',
        'pros.pl',
        'www.pros.pl',
        'optimumbhp.pl',
        'www.optimumbhp.pl',
        // znalezione przez „catalog:index --discover” dla marek bez pokrycia
        'bpbhp.pl',
        'rywal.com.pl',
        'centrumspawalnicze.pl',
        'dobryspaw.pl',
        'centrumelektronarzedzi.pl',
        '3mpolska.pl',
        'glovex.com.pl',
        'rawpol.com',
        'pol-aura.pl',
        'gloves.co.uk',
        'thesafetysupplycompany.co.uk',
        // karty masek i sprzętu MASKPOL, których wyszukiwarki nie indeksują
        'bezpieczni112.pl',
        // sklepy z szerokim katalogiem MSA
        'strefa998.pl',
        'bhp.pl',
        'sklep.arpapol.pl',
        'tmbhp.pl',
        'bhpsupply.pl',
        'marketbhp.pl',
        'balticbhp.pl',
        'esklep.krisbhp.pl',
        'aitbhp.pl',
        'behapownia.pl',
        'kams.com.pl',
        'bhp-gabi.pl',
        'specto.com.pl',
        'kingbhp.pl',
        'filimar.pl',
        'elmar-bhp.pl',
        'sklep.prohaccp.pl',
        'natare.pl',
        'sklep.arsel-bhp.pl',
        'roboczebhp.pl',
        'marelplus.pl',
        'www.marelplus.pl',
        'safeline.pl',
        'www.safeline.pl',
        'polstar.com.pl',
        'www.polstar.com.pl',
        'galmag.pl',
        'www.galmag.pl',
        'js-gloves.pl',
        'www.js-gloves.pl',
        'ppo.pl',
        'www.ppo.pl',
        'antar.pl',
        'www.antar.pl',
        'promocjabhp.pl',
        'www.promocjabhp.pl',
        'paktbhp.pl',
        'www.paktbhp.pl',
        'jaskon.pl',
        'www.jaskon.pl',
        'regera.pl',
        'www.regera.pl',
        'sklep.renex.pl',
        'customguns.pl',
        'www.customguns.pl',
        // research 2026-09: sklepy spoza indeksu + marki już w preferred_domains
        'sklep.aio.com.pl',
        'bhpstar.pl',
        'www.bhpstar.pl',
        'ferpol.pl',
        'www.ferpol.pl',
        'pol-paw.pl',
        'www.pol-paw.pl',
        'xbhp.pl',
        'www.xbhp.pl',
        'ventabebhp.com',
        'www.ventabebhp.com',
        'bhpsklep24.pl',
        'www.bhpsklep24.pl',
        'sklep.lahtipro.pl',
        'urgent.com.pl',
        'www.urgent.com.pl',
        'ardon.pl',
        'www.ardon.pl',
        'worklink.com.pl',
        'www.worklink.com.pl',
        'mapa-pro.pl',
        'www.mapa-pro.pl',
        'julex.pl',
        'www.julex.pl',
        'jagatex.pl',
        'www.jagatex.pl',
        'demar.com.pl',
        'www.demar.com.pl',
        'coba.com',
        'www.coba.com',
        'artra.com',
        'www.artra.com',
        'lemaitre-securite.com',
        'www.lemaitre-securite.com',
        'emercator.com',
        'www.emercator.com',
        'ogniochron.eu',
        'www.ogniochron.eu',
        'pwagnes.pl',
        'www.pwagnes.pl',
        'mat.konin.pl',
        'www.mat.konin.pl',
        'kask-safety.com',
        'www.kask-safety.com',
        'rs-schutz.com',
        'www.rs-schutz.com',
        'irudek.com',
        'www.irudek.com',
        'infield-safety.com',
        'www.infield-safety.com',
        'automation.honeywell.com',
        'www.automation.honeywell.com',
        'deltaplus.eu',
        'www.deltaplus.eu',
        'os-safetycenter.de',
        'www.os-safetycenter.de',
        'kortechpolska.pl',
        'www.kortechpolska.pl',
        'medicline.pl',
        'www.medicline.pl',
        'panther-bhp.pl',
        'www.panther-bhp.pl',
        'ardon.cz',
        'www.ardon.cz',
        'faraone.pl',
        'www.faraone.pl',
        'cerva.com',
        'www.cerva.com',
        'workwearnation.com',
        'www.workwearnation.com',
    ],

    /*
    | Odstęp między zapytaniami do SearXNG (Google/Qwant liczą ruch z instancji).
    | To jest ochrona przed 429 — nie liczba workerów LLM.
    */
    'search_min_interval' => (float) env('ENRICHMENT_SEARCH_MIN_INTERVAL', 1.5),

    /*
    | Ile produktów naraz szuka stron (kolejka prefetch). Model ma osobną pulę
    | (kolejka enrich, limit z Ustawień AI). Nie podnoś tego do 16 — dostaniesz 429.
    */
    'prefetch_concurrency' => max(1, min(8, (int) env('ENRICHMENT_PREFETCH_CONCURRENCY', 5))),

    /*
    | Domeny pomijane przy „catalog:index” — globalne serwisy korporacyjne mają
    | sitemapy liczone w setkach MB i prawie nic po polsku. Nadal można je
    | zaindeksować, podając host wprost: „artisan catalog:index 3m.com”.
    */
    'catalog_skip_hosts' => [
        '3m.com',
        '3mpolska.pl',
        'www.3mpolska.pl',
        'honeywell.com',
        'sps.honeywell.com',
        'kaufland.pl',
        'www.kaufland.pl',
        'agnes-ai.com',
        'app.agnes-ai.com',
        'sir.ezdrowie.gov.pl',
        'media.uvex.de',
        'whirlpool.com',
        'www.whirlpool.com',
        'd3nan4w00fsv2d.cloudfront.net',
        'd3rbxgeqn1ye9j.cloudfront.net',
    ],

    /*
    | Preferowane domeny przy wyszukiwaniu kart produktu (producent + sklepy).
    */
    'preferred_domains' => [
        'idsblast.com',
        'blastone.com',
        'novarlo.com',
        'icd.pl',
        'supon.rzeszow.pl',
        'sprzetbhp.pl',
        'gvarant.pl',
        'bhponline-24.pl',
        'fasterbhp.pl',
        'bhp-sklep.com.pl',
        'bogarobhp.pl',
        'atggloves.com',
        'www.atggloves.com',
        'atg-glovesolutions.com',
        'www.atg-glovesolutions.com',
        'ansell.com',
        'www.ansell.com',
        'delta-plus.com',
        'www.delta-plus.com',
        'demar.com.pl',
        'www.demar.com.pl',
        'demar24.pl',
        'roboczystyl.pl',
        'pros.pl',
        'www.pros.pl',
        'optimumbhp.pl',
        'www.optimumbhp.pl',
        'bpbhp.pl',
        'www.bpbhp.pl',
        'urgent.com.pl',
        'www.urgent.com.pl',
        'pl.msasafety.com',
        'msasafety.com',
        'www.msasafety.com',
        'strefa998.pl',
        'bhp.pl',
        'sklep.arpapol.pl',
        'tmbhp.pl',
        'glovex.com.pl',
        'bhpsupply.pl',
        'marketbhp.pl',
        'balticbhp.pl',
        'esklep.krisbhp.pl',
        'aitbhp.pl',
        'behapownia.pl',
        'kams.com.pl',
        'bhp-gabi.pl',
        'specto.com.pl',
        'kingbhp.pl',
        'filimar.pl',
        'elmar-bhp.pl',
        'sklep.prohaccp.pl',
        'natare.pl',
        'sklep.arsel-bhp.pl',
        'roboczebhp.pl',
        'ardon.pl',
        'www.ardon.pl',
        'ejendals.com',
        'www.ejendals.com',
        'jalas.com',
        'www.jalas.com',
        'mapa-pro.pl',
        'www.mapa-pro.pl',
        'mapa-pro.com',
        'www.mapa-pro.com',
        'marelplus.pl',
        'www.marelplus.pl',
        'worklink.com.pl',
        'www.worklink.com.pl',
        'showa-glove.com',
        'www.showa-glove.com',
        'lebonprotection.com',
        'www.lebonprotection.com',
        'cederroth.com',
        'www.cederroth.com',
        'sirsafety.com',
        'www.sirsafety.com',
        'safeline.pl',
        'www.safeline.pl',
        'secubox.eu',
        'www.secubox.eu',
        'planam.de',
        'www.planam.de',
        'ox-on.com',
        'www.ox-on.com',
        'elten.com',
        'www.elten.com',
        'ppo.pl',
        'www.ppo.pl',
        'u-power.ai',
        'dupont.com',
        'www.dupont.com',
        'dickies.com',
        'www.dickies.com',
        'julex.pl',
        'www.julex.pl',
        'jagatex.pl',
        'www.jagatex.pl',
        'polstar.com.pl',
        'www.polstar.com.pl',
        'polrok.com',
        'www.polrok.com',
        'zwoltex.pl',
        'www.zwoltex.pl',
        'galmag.pl',
        'www.galmag.pl',
        'maskpol.com.pl',
        'www.maskpol.com.pl',
        'securabc.com',
        'www.securabc.com',
        'termoizol.pl',
        'www.termoizol.pl',
        'alwit.pl',
        'www.alwit.pl',
        'js-gloves.pl',
        'www.js-gloves.pl',
        'filter-service.eu',
        'www.filter-service.eu',
        'boxmetmedical.pl',
        'www.boxmetmedical.pl',
        'cofra.it',
        'www.cofra.it',
        'protectiveindustrialproducts.com',
        'www.protectiveindustrialproducts.com',
        'york.pl',
        'www.york.pl',
        'gloria.de',
        'www.gloria.de',
        'plum.eu',
        'www.plum.eu',
        'antar.pl',
        'www.antar.pl',
        'promocjabhp.pl',
        'www.promocjabhp.pl',
        'paktbhp.pl',
        'www.paktbhp.pl',
        'jaskon.pl',
        'www.jaskon.pl',
        'regera.pl',
        'www.regera.pl',
        'sklep.renex.pl',
        'customguns.pl',
        'www.customguns.pl',
        'coba.com',
        'artra.com',
        'lemaitre-securite.com',
        'emercator.com',
        'ogniochron.eu',
        'pwagnes.pl',
        'mat.konin.pl',
        'kask-safety.com',
        'rs-schutz.com',
        'irudek.com',
        'infield-safety.com',
        'automation.honeywell.com',
        'deltaplus.eu',
        'os-safetycenter.de',
        'kortechpolska.pl',
        'medicline.pl',
        'panther-bhp.pl',
        'ardon.cz',
        'faraone.pl',
        'cerva.com',
        'workwearnation.com',
    ],

    /*
    | Publiczny klucz storefront Clerk.io (jest w HTML misterworker, nie sekret).
    | Używany, gdy GET /search zwraca 403.
    */
    'misterworker_clerk_key' => env('MISTERWORKER_CLERK_KEY', 'heKTvDthcZZhEM2SflZBzxKB499ewM8P'),
];
